---
- hosts: all 
  vars:
    ansible_python_interpreter: "/usr/bin/python2.7"
  tasks:
   - name: Install docker-py
     pip:
       name: docker
       state: present
   - name: Start Docker Container
     docker_container:
       name: spring-boot-prototype-ansible
       image: "{{ dockerImagePrefix }}/{{ projectArtifactId }}:{{ projectVersion }}"
       pull: yes
       state: started
       ports:
         - "8080:8080"
       expose:
         - 8080
